### ISSUE TITLE
Peer review - Otobo Ujah - Lab 01 #1

### ISSUE THREAD

**Issue by oujah** [reupton/progdata-class#1]
Peer Review of Lab01 for Rebecca Upton
----------------------------------------------------
Topic | Excellent | Satisfactory | Needs Work |
----------------------------|-----|-----|-----|
**Coding style** | :heavy_check_mark: | | |
**Coding strategy** |:heavy_check_mark:  | | |
**Presentation: graphs** | | |  |
**Presentation: tables** | :heavy_check_mark:|  | |
**Achievement, creativity** | :heavy_check_mark: | | |
**Ease of access** | :heavy_check_mark: | | |

Remarks:
It was good to see  that you included the **GIF** and the picture .In addition to using at least five *functionalities of GitHub markdown*, you added *creativity* to your README.md file. Great job

**Comment by reupton** [comment]
Thanks Otobo!
